### ISSUE TITLE
Moveing to hapijs

### ISSUE THREAD

**Issue by hueniverse** [hapijs/university#133]
I moved the project to the hapijs organization, renamed it `university` and added [Zoe](https://github.com/zoe-1) as maintainer. I'll let him take it on from here.

@zoe-1 you might want to add a full name to your profile and to the Readme as I find it makes it easier for people to engage and relate to others.

Go ahead and get another assignment going...!

**Comment by AdriVanHoudt** [comment]
s/moveing/moving in title

Also do you have any remarks on the discussions or is this the "official give over to the community"?

@zoe-1 I also think having some form of identification helps
And maybe start with a side repo to start drafting assignments and solutions?

**Comment by zoe-1** [comment]
@hueniverse  Thank you for opportunity to maintain this project.
I will fill out my profile and start working on a new assignment tomorrow :-)
By the way, I am a male. 
Cheers!

@AdriVanHoudt Good suggestion about the side repo.
I just drove 6 hours from VA Beach to Pennsylvania.  So, my mind is not super clear right now. 
Let's put more thought into this tomorrow.

**Comment by hueniverse** [comment]
@zoe-1 Zoe is my daughter's name :-)

**Comment by AdriVanHoudt** [comment]
@zoe-1 hmm yes drafting the assignment in here could work, drafting the solution, as talked about before, not so much, people need to learn from other's PRs not a given solution imo

**Comment by AdriVanHoudt** [comment]
This issue can be closed since we've started going again also not sure who handles the twitter account for hapi but a shoutout might help increase the amount of participants @hueniverse ?

**Comment by zoe-1** [comment]
@AdriVanHoudt   Will close post soon.  Leaving latest issues up for a bit while we transition to new repo.  This will help people see the story behind the transition etc.  Holiday weekend started here so interaction will be minimal for next two days.
