### ISSUE TITLE
Travis build error and npm install failure

### ISSUE THREAD

**Issue by zoe-1** [hapijs/university#143]
After uploading edits to master. 
Travis did not pass tests.
```
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
```
Based on error messages it looks like npm fails to install with iojs. 
Looks like iojs is having issues. node.js tests pass.

**Comment by zoe-1** [comment]
Yes, it was iojs several minutes later re-ran test and they all passed.

**Comment by zoe-1** [comment]
3.09s$ nvm install iojs
######################################################################## 100.0%
WARNING: checksums are currently disabled for io.js
Now using io.js v2.2.0
$ node --version
v2.2.0
$ npm --version
2.11.0
$ nvm --version
0.23.3
5.37s$ npm install 
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v2.2.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v2.2.0/bin/npm" "install"
npm ERR! node v2.2.0
npm ERR! npm  v2.11.0
npm ERR! code ESSL
npm ERR! SSL Error: https://registry.npmjs.org/hoek does not support SSL
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/hapijs/university/npm-debug.log
The command "eval npm install " failed. Retrying, 2 of 3.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v2.2.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v2.2.0/bin/npm" "install"
npm ERR! node v2.2.0
npm ERR! npm  v2.11.0
npm ERR! code ESSL
npm ERR! SSL Error: https://registry.npmjs.org/hoek does not support SSL
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/hapijs/university/npm-debug.log
The command "eval npm install " failed. Retrying, 3 of 3.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v2.2.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v2.2.0/bin/npm" "install"
npm ERR! node v2.2.0
npm ERR! npm  v2.11.0
npm ERR! code ESSL
npm ERR! SSL Error: https://registry.npmjs.org/glue does not support SSL
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/hapijs/university/npm-debug.log
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.

**Comment by AdriVanHoudt** [comment]
Io.js updated npm which has an SSL bug so that is breaking it, just wait on a patch from io.js and rerun the tests on io.js

**Comment by AdriVanHoudt** [comment]
to be more precise it was more of io.js's fault it seems see https://github.com/nodejs/io.js/issues/1850

**Comment by zoe-1** [comment]
Thanks @AdriVanHoudt good to know.

**Comment by AdriVanHoudt** [comment]
looks like a new version is here, try rerunning the builds on travis

**Comment by zoe-1** [comment]
travils fails on hapijs/university.  And, I do not know why?
<hr/>
```
Using worker: worker-linux-docker-ad8f5044.prod.travis-ci.org:travis-linux-6
system_info
Build system information
Build language: node_js
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
0.09s$ git clone --depth=50 --branch=master git://github.com/hapijs/university.git hapijs/university
Cloning into 'hapijs/university'...
remote: Counting objects: 220, done.
remote: Total 220 (delta 0), reused 0 (delta 0), pack-reused 220
Receiving objects: 100% (220/220), 131.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (78/78), done.
Checking connectivity... done.
$ cd hapijs/university
$ git checkout -qf 99fed335520e9155e4a30c0c5cf5892174b652f3
fatal: reference is not a tree: 99fed335520e9155e4a30c0c5cf5892174b652f3
The command "git checkout -qf 99fed335520e9155e4a30c0c5cf5892174b652f3" failed and exited with 128 during .
Your build has been stopped.
```
<hr/>
It tried to:
git checkout -qf 99fed335520e9155e4a30c0c5cf5892174b652f3
and fails.  I search the repo and this commit id is not there. 
I am not quite sure what is happening.  It could be a permssions issue because I pushed to the repo and I am not set up right with travis?  I am not quite. sure.  

But, I think this relates to @rutaihwa 's travis failing.  He most synched up with the repo. 

Possibly, Travis does not like git commit --amend.  This may be causing the issue. I amended a couple commits when working on them.  Could this cause the problem?  
Any advice would be appreciated. 

A couple days ago iojs was failing not 0.10 and 0.12 fail too.

**Comment by zoe-1** [comment]
Note: I did not amend any commits after pushing them to remote origin.

**Comment by nlf** [comment]
i restarted a different build for a commit that actually exists and this problem went away, you're all green again :+1: sometimes travis is just weird

**Comment by zoe-1** [comment]
@nlf Thanks!
