### ISSUE TITLE
About assignment 6: my tls server connection wont respond

### ISSUE THREAD

**Issue by rutaihwa** [hapijs/university#150]
I have tried to configure the tls connection as per #144 on my commit [ here ] (https://github.com/rutaihwa/university/blob/assignment6/lib/start.js) but whenever I try  to access the web-tls, I get no response, when am I doing wrong?

**Comment by zoe-1** [comment]
I cloned your project and ran it. It works fine :-)
To access the tls server, just go to localhost:8000/home in your browser and it redirects to 
https://localhost:8001/home which is the TLS route.  

When I started your server, the server connections both printed out.
The below worked fine:
```
    var web = server.connections[0];
    var webTls = server.connections[1];

    // Logging started server
    console.log('Web server started at: ' + web.info.uri);
    console.log('WebTLS server started at: ' + webTls.info.uri);
```
If you want another way to access these connections:
```
var web = server.select('web');
var web-tls server.select('web-tls');
```

**Comment by rutaihwa** [comment]
@zoe-1 I guess my browser was acting wicked, it now work on my end. Thanks!

**Comment by zoe-1** [comment]
@rutaihwa glad you solved it :-)
