### ISSUE TITLE
helps for Assignment 7 

### ISSUE THREAD

**Issue by zoe-1** [hapijs/university#153]
<b>Assignment7</b> will cover the important subjects: form submissions, validation, authentication, and authorization. To prepare, work through the below resources:
* Saul Madox @poeticninja wrote a very nice tutorial on hapijs authentication and authorization at<br/>
  [Hapi Authentication and Authorization](https://medium.com/@poeticninja/authentication-and-authorization-with-hapi-5529b5ecc8ec)
* Plus, he made this [github repo ](https://github.com/poeticninja/hapi-authentication-and-authorization) providing very nice sample code illustrating how to use [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie).
* A read through the [hapi-auth-cookie docs](https://github.com/hapijs/hapi-auth-cookie) will be helpful too.

Knowledge of the above resources will help greatly with the next assignment.
I plan to post a proposal for assignment7 today or tomorrow.
Assignment7 should be posted on Friday June 12 or Saturday June 13th.  

Hapi Coding!

**Comment by rutaihwa** [comment]
Great!
