### ISSUE TITLE
Re-write the university

### ISSUE THREAD

**Issue by zoe-1** [hapijs/university#185]
### Time to re-write the university 
2016 has arrived and Node and hapijs have rapidly progressed and the university has become outdated.  So, plan to re-write the university.

* node is v4.3.0 LTS but the university was written when it was v12.
  Nodejs LTS schedule [here](https://github.com/nodejs/LTS#lts_schedule)
* hapi is at v13 but the university was written using v8.
* nodejs now supports ECMAScript 2015 (ES6). However, the university has no es6 code in it
  and it would not pass current hapi linting standards.
    - Syntactic sugar which hapi's linting enforces
        * shorthand:
            - () => {} versus function () {}
            - { objectKeys }
        * let and const for performance.
    - See [this](https://nodejs.org/en/docs/es6/) for more details.

### In next version would like to:
  - keep  most original assignments.
  - definitely want to add:
      * cors
      * db support
  - considering the addition of:
      * hawk
        with long term goal of using hawk to prepare to do something with [OZ](https://github.com/hueniverse/oz).
      * nes - would also like to fit [hapiness](https://github.com/hapijs/nes) into the project.
      * a hapi proxy server
  - remove
      * hapi-auth-basic
          Seems most people would be interested in using hapi-auth-cookie or hapi-auth-hawk.
  - rewrite assignments
  - rewrite guides

### multiple university repos 
In the future, would like the university to have two or three repos named:
  * **university**:
    -  serve traditional web pages.
    -  home to web api serving data to various clients: university web pages and university-client.
  * **university-client**:
      - SPA application or hybrid spa application running on a hapi server.
      - consumes the **university** api making cors requests.
      - Additionally, would like to use [request](https://www.npmjs.com/package/request) to consume the university api in the client repository.
        - this mean university-client would consume our api through two methods: one, as a web page 
          making CORS requests. The other would be the server using the request library to make requests from the api similar to how someone would use `curl` to make http requests.
  * (possibly) **university-proxy**
            Illustrate how to use hapi as a proxy server for an api.

Feedback welcomed :-)

**Comment by simon-p-r** [comment]
@zoe-1 good ideas, I like the idea of a hapi serving client talking to an api server!

**Comment by zoe-1** [comment]
Added [nes](https://github.com/hapijs/nes) into discussion about the next version too.

**Comment by Miguel-Herrero** [comment]
Hi @zoe-1 ! This last week I have been doing the University assignments and I had to adapt it to the latest versions (as I saw that everything was written/solved with past versions of packages). Besides I added some assignments to the Wiki.

Here is [my fork](https://github.com/Miguel-Herrero/university) with `myAssignment`s branches, in case it would be of any help.

I would be interested in helping with updating the Assignments, in case you want collaborators.

**Comment by Miguel-Herrero** [comment]
And some feedback:

0. Learn how to **documentate the API** with hapij's [lout](https://github.com/hapijs/lout)
0. Separate `auth`, `config` and `database` files (in previous Assignments it would be our `users.json` file) into **subfolders**. [One example I liked](https://github.com/bartonhammond/snowflake-hapi-openshift/tree/master/src)
0. **Auth with [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2)**, as JWT are a standard too and they can be used for _mobile devices and apps that use our hapijs API_ (they cannot store cookies but they can store a secure token)
0. Simple connection to a [MongoDB](https://mongolab.com)? Or how to **integrate a database** connection into the API…

**Comment by jd73** [comment]
I think it's a great idea. I'm fairly new to Node and Hapi. The first few assignments (the ones that you have already modernized a bit) have been a very helpful start so far. Now I'm getting to some of the ones yet to be updated and going back to a slightly older style is a bit jarring.

Some of the additional topics you mentioned covering (SPA, DB support, other auth schemes etc...) also seem like they would be very useful additions.

Like I said, I am pretty new to Node and Hapi, but I would be willing to help out where I can.

**Comment by zoe-1** [comment]
@jd73 It is good to have your feedback. Glad you are interested in participating. 
Plan to re-write the assignments ( [three are already prepared here](https://github.com/zoe-1/udev-client/tree/master/assignments) ) and need to re-write the README too.  After that, want to recruit people to participate and fulfill the assignments as a group. 

It will be a good opportunity to learn how to work in a distributed environment / distributed team using github.  And, of course, participants will learn much about hapi too :-)

**Comment by Miguel-Herrero** [comment]
@zoe-1 sorry to bother but in your rewritten [Assignment4](https://github.com/zoe-1/udev-client/blob/master/assignments/a0.0.4.md) you have written: 
> Using the hapi-auth-cookie plugin:

Shouldn't it be?:
> Using the hapi-auth-basic plugin:

**Comment by zoe-1** [comment]
@Miguel-Herrero good to have your input. 
In respect to assignment4, as mentioned above was planning to remove hapi-auth-basic from the project. Currently, hapi-auth-basic is used in the project and later replaced by hapi-auth-cookie. 
This is a bit redundant so was planning to use hapi-auth-cookie right from the start.

**Comment by damianesteban** [comment]
I'm looking forward to this.  Any idea as to when it may start?

**Comment by zoe-1** [comment]
@damianesteban Glad you are interested.  
Currently, plan to update [assignment7](https://github.com/hapijs/university/issues/155) and [assignment8](https://github.com/hapijs/university/issues/167) to ES6. 
Then, want to move forward with a re-write.

**Comment by damianesteban** [comment]
@zoe-1 Very cool, thanks for the update.  Perhaps I will submit a PR next week.

**Comment by zoe-1** [comment]
@damianesteban good to hear from you. 
Would you be able to help with this #201? Cheers!

**Comment by zoe-1** [comment]
@Miguel-Herrero @jd73 @simon-p-r  that above invitation is open to you too.
Would appreciate your help with this #201?

**Comment by Miguel-Herrero** [comment]
@zoe-1 Sure! :+1:

**Comment by jd73** [comment]
I'll give it a once over.

**Comment by zoe-1** [comment]
@jd73 and @Miguel-Herrero thanks for the help with the reviews. Project is updated.

**Comment by Miguel-Herrero** [comment]
Thanks to you @zoe-1. Excellent job!! Congratulations for your efforts

**Comment by damianesteban** [comment]
Let me know if there are any other issues I can help with.

**Comment by zoe-1** [comment]
@Miguel-Herrero Thank you for the encouraging words :-)
But, I cannot take all credit the updates. Others also contributed to assignments.
For example, @apoorvakorde made significant contributions to the earlier assignments 1-6. 
Cheers @apoorvakorde!

**Comment by zoe-1** [comment]
@damianesteban future development will be posted in the issues list.

**Comment by zoe-1** [comment]
I am closing this because most of the re-write is done. Every branch / assignment is updated to ES6. Plus, people new to the university may be confused by it's title. Currently, writing an overview of issues related to developing the university with multiple repos: client, api, data, proxy etc.  Will soon open an issue for discussion of this.
