### ISSUE TITLE
new label 'community PR' ?

### ISSUE THREAD

**Issue by zoe-1** [hapijs/university#205]
per @jd73 discussion #200:
> If I have my own solution to an assignment that a PR already exists for and has good discussion in, 
> is  it better for me to focus on discussing my ideas in my own PR or in the 'community' PR?

Think through 'communityPR' and explanation. Similar to early days of the university, the first labelling of a PR as 'assignment' signified most discussion related to the assignment occurred there and it would be refactored to be an example PR for the assignment.  This would be a 'community PR'.  Main comments and discussion for the assignment will occur there. Plus, the code is refactored to be a model for others to study in order to complete there assignments.  More advanced developers may compete in order to have their PR accepted as the 'communityPR'.
 
@todo improve explanation of this ./guides/groupDevelopment.md. 

Is everyone OK with the 'communityPR' concept? What are your thoughts?

**Comment by Miguel-Herrero** [comment]
I prefer this “community PR” model, as all discussion would be placed in the same PR. Having said that, “own PRs” could be the place for discussing proposed changes to others' PR, in case that person would need some specific explanation or hint.

**Comment by jd73** [comment]
I think something along those lines is a good idea. I envision it as a place to discuss the core concepts of the lesson and to see a single generally high quality solution in one place as well as the thought process that went into that particular solution. Also, after the solution is accepted it could be useful to link back to the PR in the assignments as a form of living documentation.

**Comment by zoe-1** [comment]
@jd73 and @Miguel-Herrero,  I agree with you both. Good suggestions :-)

**Comment by zoe-1** [comment]
@Miguel-Herrero and @jd73 
When you have a minute, take a look at [new group development guide](https://github.com/zoe-1/hapijs-university/blob/master/guides/groupDevelopment.md) and let me know what your think. 
Specifically, what do you think about using the terms: 
* personalPR
* communityPR (already discussed above)
* solutionPR

**Comment by zoe-1** [comment]
Made a bunch of edits.
I'm happy with the current solution and plan to merge it in unless
more suggestions are made.

**Comment by Miguel-Herrero** [comment]
:+1: for your proposals

**Comment by jd73** [comment]
I like it :+1:

**Comment by zoe-1** [comment]
#206 closes this.
